CREATE DATABASE CADASTRO_LOJA

USE CADASTRO_LOJA

--CRIAÇÃO DA TABELA CLIENTE
CREATE TABLE CLIENTE(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(20) NOT NULL,
SOBRENOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) UNIQUE,
DATA_NASC DATE NOT NULL,
DATA_EXPIRACAO DATE NOT NULL,
DATA_CADASTRO DATE NOT NULL,
DATA_ULTIMA_ALTERACAO DATE
)

--INSERIR DADOS NA TABELA CLIENTE
INSERT INTO CLIENTE(NOME, SOBRENOME, CPF, DATA_NASC, DATA_EXPIRACAO, DATA_CADASTRO, DATA_ULTIMA_ALTERACAO)
	VALUES	('ERICK', 'ALVES', 12345678910, '1987/04/16', '2025/01/10', '2024/01/10', NULL)

--CRIAÇÃO DA TABELA CATEGORIA
CREATE TABLE CATEGORIA(
ID INT PRIMARY KEY IDENTITY,
NOME_CATEGORIA VARCHAR(30),
)

--CRIAÇÃO DA TABELA PRODUTO
CREATE TABLE PRODUTO(
ID INT PRIMARY KEY IDENTITY,
ID_CATEGORIA INT,
NOME VARCHAR(50) NOT NULL,
PRECO_UNIT MONEY NOT NULL,
DATA_CADASTRO DATE NOT NULL,
QUANTIDADE INT,
DATA_ULTIMA_ALTERACAO DATE,
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
)

--CRIAÇÃO DA TABELA PRECO
CREATE TABLE PRECO(
ID INT PRIMARY KEY IDENTITY,
ID_PRODUTO INT,
VALOR_VENDA MONEY NOT NULL,
DATA_EXPIRACAO_VALOR DATE NOT NULL,
DATA_CADASTRO DATE NOT NULL,
DATA_ULTIMA_ALTERACAO DATE,
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
)

--CRIAÇÃO DA TABELA ITENS  COMPRA
CREATE TABLE ITENS_COMPRA(
ID INT PRIMARY KEY IDENTITY,
ID_CLIENTE INT,
ID_PRODUTO INT,
QUANTIDADE INT NOT NULL,
VALOR_TOTAL MONEY NOT NULL,
DATA_COMPRA DATE NOT NULL,
DATA_CADASTRO DATE NOT NULL,
DATA_ULTIMA_ALTERACAO DATE,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
)

--CRIAÇÃO DA TABELA ITENS FATURAMENTO
CREATE TABLE FATURAMENTO(
ID INT PRIMARY KEY IDENTITY,
ID_ITENS_COMPRA INT,
VALOR_LUCRO MONEY,
FOREIGN KEY (ID_ITENS_COMPRA) REFERENCES ITENS_COMPRA(ID)
)

--CRIAÇÃO DE PROCEDURE DE INSERT PARA TABELA PRODUTO
CREATE OR ALTER PROC [dbo].[SP_INSERT_PRODUTO](
		@ID_CATEGORIA INT,
		@NOME VARCHAR(50),
		@PRECO_UNIT MONEY,
		@DATA_CADASTRO DATE,
		@QUANTIDADE INT,
		@DATA_ULTIMA_ALTERACAO DATE
)
AS
/*
DOCUMENTAÇÃO
ARQUIVO FONTE.....: SP_INSERT_PRODUTO.SQL
OBJETIVO..........: INSERIR DADOS NA TABELA PRODUTO
AUTOR.............: ERICK ALVES 
DATA..............: 09/01/2024
EX................: EXEC [dbo].[SP_INSERT_PRODUTO] @ID_CATEGORIA, @NOME, @PRECO_UNIT, @DATA_CADASTRO, @QUANTIDADE, @DATA_ULTIMA_ALTERACAO)
*/
	BEGIN
		INSERT INTO PRODUTO(ID_CATEGORIA, NOME, PRECO_UNIT, DATA_CADASTRO, QUANTIDADE, DATA_ULTIMA_ALTERACAO)
			VALUES	(@ID_CATEGORIA, @NOME, @PRECO_UNIT, @DATA_CADASTRO, @QUANTIDADE, @DATA_ULTIMA_ALTERACAO)
	END
GO

--CRIAÇÃO DE PROCEDURE DE INSERT PARA TABELA PRECO
CREATE OR ALTER PROC [dbo].[SP_INSERT_PRECO](
		@ID_PRODUTO INT,
		@VALOR_VENDA MONEY,
		@DATA_EXPIRACAO_VALOR DATE,
		@DATA_CADASTRO DATE,
		@DATA_ULTIMA_ALTERACAO DATE
)
AS
/*
DOCUMENTAÇÃO
ARQUIVO FONTE.....: SP_INSERT_PRODUTO.SQL
OBJETIVO..........: INSERIR DADOS NA TABELA PRECO
AUTOR.............: ERICK ALVES 
DATA..............: 09/01/2024
EX................: EXEC [dbo].[SP_INSERT_PRECO] @ID_PRODUTO, @VALOR_VENDA, @DATA_EXPIRACAO_VALOR, @DATA_CADASTRO, @DATA_ULTIMA_ALTERACAO
*/
	BEGIN
		INSERT INTO PRECO(ID_PRODUTO, VALOR_VENDA, DATA_EXPIRACAO_VALOR, DATA_CADASTRO, DATA_ULTIMA_ALTERACAO)
			VALUES	(@ID_PRODUTO, @VALOR_VENDA, @DATA_EXPIRACAO_VALOR, @DATA_CADASTRO, @DATA_ULTIMA_ALTERACAO)
	END
GO

--CRIAÇÃO DE PROCEDURE DE INSERT PARA TABELA ITENS COMPRAS
CREATE OR ALTER PROC [dbo].[SP_INSERT_ITENS_COMPRA](
		@ID_CLIENTE INT,
		@ID_PRODUTO INT,
		@QUANTIDADE INT,
		@VALOR_TOTAL MONEY,
		@DATA_COMPRA DATE,
		@DATA_CADASTRO DATE,
		@DATA_ULTIMA_ALTERACAO DATE
)
AS
/*
DOCUMENTAÇÃO
ARQUIVO FONTE.....: SP_INSERT_PRODUTO.SQL
OBJETIVO..........: INSERIR DADOS NA TABELA ITENS_COMPRA
AUTOR.............: ERICK ALVES 
DATA..............: 09/01/2024
EX................: EXEC [dbo].[SP_INSERT_ITENS_COMPRA] @ID_CLIENTE, @ID_PRODUTO, @QUANTIDADE, @VALOR_TOTAL, @DATA_COMPRA, @DATA_CADASTRO, @DATA_ULTIMA_ALTERACAO
*/
	BEGIN
		INSERT INTO ITENS_COMPRA(ID_CLIENTE, ID_PRODUTO, QUANTIDADE, VALOR_TOTAL, DATA_COMPRA, DATA_CADASTRO, DATA_ULTIMA_ALTERACAO)
			VALUES	(@ID_CLIENTE, @ID_PRODUTO, @QUANTIDADE, @VALOR_TOTAL, @DATA_COMPRA, @DATA_CADASTRO, @DATA_ULTIMA_ALTERACAO)
	END
GO

--CRIAR UMA FUNCTION PARA CALCULAR PERCENTAGEM
CREATE OR ALTER FUNCTION [dbo].[FUNC_PRECO](
		@ID_PRODUTO INT
		) RETURNS MONEY
AS
/*
DOCUMENTAÇÃO
ARQUIVO FONTE.....: FUNC_PRECO.SQL
OBJETIVO..........: CALCULAR PRECO UNITARIO ACRESCENTANDO PERCENTAGEM
AUTOR.............: ERICK ALVES
DATA..............: 09/01/2024
EX................: SELECT dbo.FUNC_PRECO (@ID_PRODUTO) AS PRECO_ATUALIZADO
*/
	BEGIN 
		DECLARE @PRECO_NOVO MONEY


		SELECT @PRECO_NOVO = PRECO_UNIT + (PRECO_UNIT * 50 / 100)
			FROM PRODUTO
		WHERE ID = @ID_PRODUTO

		RETURN @PRECO_NOVO
	END
GO

--CRIAR UM TRIGGER ATUALIZAR A TABELA PRECO
CREATE OR ALTER TRIGGER TRG_PRECO_NOVO
ON PRECO
AFTER INSERT
AS
/*
DOCUMENTAÇÃO
ARQUIVO FONTE.....: [dbo].[TRG_PRECO_NOVO].SQL
OBJETIVO..........: INSERIR E ATUALIZAR TABELA PRECO
AUTOR.............: ERICK ALVES
DATA..............: 09/01/2024
EX................: SELECT [dbo].[TRG_PRECO_NOVO] (1)
*/
	BEGIN
		DECLARE @ID_PRECOI INT
		DECLARE @ID_PRODUTOSI INT
		DECLARE @VALOR_VENDAI MONEY
		DECLARE @DATA_CADASTROI DATE
		DECLARE @DATA_EXPIRACAOI DATE

		SET @ID_PRECOI = SCOPE_IDENTITY()
		SET @ID_PRODUTOSI = (SELECT ID_PRODUTO FROM inserted)
		SET @DATA_CADASTROI = (SELECT DATA_CADASTRO FROM inserted)
		SET @VALOR_VENDAI = [dbo].[FUNC_PRECO](1)
		SET @DATA_EXPIRACAOI = DATEADD(YEAR, 1, @DATA_CADASTROI)

		UPDATE PRECO
			SET VALOR_VENDA = @VALOR_VENDAI,
				DATA_EXPIRACAO_VALOR = @DATA_EXPIRACAOI
		WHERE ID = @ID_PRECOI
	END
GO

--CRIAR UMA FUNCTION PARA CALCULAR VALOR TOTAL
CREATE OR ALTER FUNCTION FNC_VALOR_TOTAL(
		@ID_PRODUTO INT,
		@QUANTIDADE INT
		)
		RETURNS DECIMAL(10,2)
AS
/*
Documentação
Arquivo Fonte.....: FNC_VALOR_TOTAL.SQL
Objetivo..........: CALCULAR VALOR TOTAL
Autor.............: ERICK ALVES
Data..............: 29/12/2023
Ex................: SELECT [dbo].[FNC_VALOR_TOTAL](@ID_PRODUTO, @QUANTIDADE) AS VALOR_TOTAL
*/
	BEGIN
		DECLARE @VALOR_TOTAL_COMPRA MONEY
		DECLARE @PRECO_VENDA MONEY

		SELECT @PRECO_VENDA = PC.VALOR_VENDA  
			FROM PRODUTO P
			INNER JOIN PRECO PC ON P.ID = PC.ID_PRODUTO
			INNER JOIN ITENS_COMPRA IC ON P.ID = IC.ID_PRODUTO
		WHERE P.ID = @ID_PRODUTO

		SET @VALOR_TOTAL_COMPRA = @PRECO_VENDA * @QUANTIDADE

		RETURN @VALOR_TOTAL_COMPRA
	END
GO

--CRIAR UMA FUNCTION PARA CALCULAR LUCRO
CREATE OR ALTER FUNCTION [dbo].[FUNC_LUCRO](
		@ID_ITENS_COMPRA INT
		) RETURNS MONEY
AS
/*
DOCUMENTAÇÃO
ARQUIVO FONTE.....: FUNC_PRECO.SQL
OBJETIVO..........: CALCULAR PRECO UNITARIO ACRESCENTANDO PERCENTAGEM
AUTOR.............: ERICK ALVES
DATA..............: 09/01/2024
EX................: SELECT dbo.FUNC_PRECO (@ID_ITENS_COMPRA) AS PRECO_ATUALIZADO
*/
	BEGIN
		DECLARE @VALOR_UNIT MONEY
		DECLARE @QUANTIDADE INT
		DECLARE @VALOR_VENDA MONEY
		DECLARE @LUCRO MONEY

		SELECT @VALOR_VENDA = PC.VALOR_VENDA, @VALOR_UNIT = P.PRECO_UNIT, @QUANTIDADE = IC.QUANTIDADE
			FROM PRODUTO P
			INNER JOIN PRECO PC ON P.ID = PC.ID_PRODUTO
			INNER JOIN ITENS_COMPRA IC ON P.ID = IC.ID_PRODUTO
		WHERE IC.ID = @ID_ITENS_COMPRA

		SET @LUCRO = (@VALOR_VENDA - @VALOR_UNIT) * @QUANTIDADE

		RETURN @LUCRO
	END
GO

--CRIAR TRIGGER PARA ATUALIZAR TABELA FATURAMENTO
CREATE OR ALTER TRIGGER TRG_FATURAMENTO
ON ITENS_COMPRA
AFTER INSERT
AS
/*
DOCUMENTAÇÃO
ARQUIVO FONTE.....: [dbo].[TRG_VENDA].SQL
OBJETIVO..........: INSERIR E ATUALIZAR TABELA PRECO
AUTOR.............: ERICK ALVES
DATA..............: 09/01/2024
EX................: SELECT [dbo].[TRG_VENDA] (1)
*/
	BEGIN
		DECLARE @ID_ITENSI INT
		DECLARE @VALOR_FATURADOI MONEY

		SELECT @ID_ITENSI = ID FROM inserted
		SELECT @VALOR_FATURADOI = (SELECT  [dbo].[FUNC_LUCRO](@ID_ITENSI))
	

        BEGIN
            UPDATE FATURAMENTO
                SET ID_ITENS_COMPRA = @ID_ITENSI,
                    VALOR_LUCRO = @VALOR_FATURADOI
                    WHERE ID = @ID_ITENSI
        END
    END
GO

--SELECIONAR OS PRODUTOS COM VALOR PARA VENDA ACIMA DE 100R$;
SELECT ID, NOME, PRECO_UNIT FROM PRODUTO
WHERE PRECO_UNIT >= 100

--SELECIONAR OS PRODUTOS COM MAIOR QUANTIDADE EM ESTOQUE;
SELECT ID, NOME, QUANTIDADE 
	FROM PRODUTO
ORDER BY QUANTIDADE DESC

--SELECIONAR O VALOR TOTAL LUCRADO EM SEIS MESES. OBSERVAÇÃO: SERÁ EM SEIS MESES DE ACORDO COM A DATA EM QUE ESSE SELECT É EXECUTADO, OU SEJA NÃO PODE TER CÓDIGO MOCADO;
SELECT SUM(F.VALOR_LUCRO) AS VALOR_LUCRO, IT.DATA_COMPRA
	FROM ITENS_COMPRA IT
	INNER JOIN FATURAMENTO F ON IT.ID = F.ID_ITENS_COMPRA
WHERE IT.DATA_COMPRA >= DATEADD(MONTH, -6, GETDATE())
GROUP BY F.VALOR_LUCRO, IT.DATA_COMPRA
ORDER BY F.VALOR_LUCRO DESC 

--SELECIONAR OS CLIENTES QUE REALIZARAM MAIS COMPRA EM MENOS DE 1 ANO
SELECT ID_CLIENTE, COUNT(*) AS NUMEROS_COMPRAS
	FROM ITENS_COMPRA
WHERE DATA_COMPRA >= DATEADD(YEAR, -1, GETDATE())
GROUP BY ID_CLIENTE
ORDER BY NUMEROS_COMPRAS